name: ray
channels:
  - conda-forge
  - defaults
dependencies:
  - bison
  - bzip2
  - ca-certificates
  - certifi
  - cmake
  - curl
  - cython
  - expat
  - flask
  - flex
  - libcurl
  - libedit
  - libffi
  - libgcc
  - libiconv
  - libssh2
  - libuv
  - m4
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - requests
  - rhash
  - setuptools
  - six
  - sqlite
  - socat
  - thrift
  - tk
  - wheel
  - xz
  - zlib
  - pip:
    - attrs
    - click
    - colorama
    - flatbuffers
    - funcsigs
    - more-itertools
    - numpy
    - pluggy
    - psutil
    - py
    - pytest
    - pyyaml
    - ray
    - redis

